{% set name = "law" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d61165e86717f335b180865f0cb541180da7ae1436f264650c04cae6b012d9c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - six >=1.10
    - luigi >=2.8.2

test:
  imports:
    - law
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/riga/law
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Use law to build complex and large-scale task workflows.
  description: |
    Use law to build complex and large-scale task workflows. It is build on top of luigi and adds
    abstractions for run locations, storage locations and software environments. Law strictly
    disentangles these building blocks and ensures they remain interchangeable and
    resource-opportunistic.

    Key features:
    - CLI with auto-completion and interactive status and dependency inspection.
    - Remote targets with automatic retries and local caching: WebDAV, HTTP, Dropbox, SFTP, all WLCG
      protocols (srm, xrootd, rfio, dcap, gsiftp, ...)
    - Automatic submission to batch systems from within tasks: HTCondor, LSF, gLite, ARC
    - Environment sandboxing, configurable on task level: Docker, Singularity, Sub-Shells
  doc_url: https://law.readthedocs.io
  dev_url: https://github.com/riga/law

extra:
  recipe-maintainers:
    - riga
